'use client';

/* eslint-disable @next/next/no-img-element */

import { useCallback, useEffect, useState } from 'react';

const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001/api';

export type CaptchaState = { token: string; answer: string };

/**
 * Renders a server-issued CAPTCHA challenge.
 *
 * The image is an SVG data-URL generated by our own backend (no third-party
 * script, so nothing extra in the CSP and no tracking pixel). The `token` is an
 * opaque signed value the server uses to verify the answer — the client never
 * learns the expected code, so a scripted client gains nothing by reading it.
 */
export default function Captcha({
  onChange,
  label = 'Type the characters shown'
}: {
  onChange: (state: CaptchaState) => void;
  label?: string;
}) {
  const [image, setImage] = useState<string | null>(null);
  const [token, setToken] = useState('');
  const [answer, setAnswer] = useState('');
  const [loading, setLoading] = useState(false);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const res = await fetch(`${API_URL}/auth/captcha`, { credentials: 'include' });
      const data = await res.json();
      setImage(data.image);
      setToken(data.captchaToken);
      setAnswer('');
      onChange({ token: data.captchaToken, answer: '' });
    } catch {
      setImage(null);
    } finally {
      setLoading(false);
    }
  }, [onChange]);

  useEffect(() => {
    load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleAnswer = (value: string) => {
    setAnswer(value);
    onChange({ token, answer: value });
  };

  return (
    <div>
      <label htmlFor="captcha" className="mb-1.5 block text-sm font-medium text-neutral-700">
        {label}
      </label>
      <div className="flex items-center gap-3">
        <div className="flex h-[50px] w-[160px] shrink-0 items-center justify-center overflow-hidden rounded-lg border border-neutral-200 bg-white">
          {image ? (
            <img src={image} alt="CAPTCHA challenge" className="h-full w-full" />
          ) : (
            <span className="text-xs text-neutral-400">{loading ? 'Loading…' : 'Unavailable'}</span>
          )}
        </div>
        <button
          type="button"
          onClick={load}
          title="Get a new image"
          aria-label="Refresh CAPTCHA"
          className="rounded-lg border border-neutral-200 p-2 text-neutral-600 transition hover:bg-neutral-100 hover:text-neutral-900"
        >
          <svg viewBox="0 0 24 24" fill="none" strokeWidth={1.8} stroke="currentColor" className="h-4 w-4">
            <path strokeLinecap="round" strokeLinejoin="round" d="M16.023 9.348h4.992V4.356m-4.992 4.992l3.181-3.183a8.25 8.25 0 00-13.803 3.7M4.031 9.865v4.992m0 0h4.992m-4.993 0l3.181 3.183a8.25 8.25 0 0013.803-3.7" />
          </svg>
        </button>
      </div>
      <input
        id="captcha"
        autoComplete="off"
        spellCheck={false}
        className="mt-2 block w-full rounded-xl border border-neutral-200 bg-neutral-50 px-4 py-2.5 text-sm uppercase tracking-widest text-neutral-900 placeholder-neutral-400 outline-none transition focus:border-emerald-500 focus:ring-4 focus:ring-emerald-100"
        placeholder="Enter code"
        value={answer}
        onChange={(e) => handleAnswer(e.target.value)}
      />
    </div>
  );
}
